// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufwptcqxikxomjmpfxsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmd3B0Y3F4aWt4b21qbXBmeHNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTA5NzksImV4cCI6MjA2MDM4Njk3OX0.P65ckfT7f4IWHJzKJzSRSF9-d_O3qegLqgIUikoTyTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);